# -*- coding: utf-8 -*-
"""SEQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GO_FG7h378S0rmDWAJ7v9iOr_4oMnDL
"""

import subprocess


# Filename
file2 = 'DataACM.py'
file3 = '3025term_tf_idf.py'

# Function to run a Python file and check if it was successful
def run_script(file_path):
    try:
        result = subprocess.run(['python3', file_path], check=True)
        return result.returncode == 0  #True if the script was successful
    except subprocess.CalledProcessError:
        return False  #False if the script failed


if run_script(file2):
    if run_script(file3):
    else:
        print(f"Execution failed at: {file3}")
else:
    print(f"Execution failed at: {file2}")
